apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: chat-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: backend
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30080    # Match containerPort in Kind config
  type: NodePort
