apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: chat-app 
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Note: PVs are *not* namespaced, but it's safe to add for clarity
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data
