apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: chat-app
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  clusterIP: None              # 👈 Makes it headless
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
