apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
  namespace: chat-app
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
 MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
 MONGO_INITDB_ROOT_PASSWORD: bW9uZ28xMjM=
 JWT_SECRET: Mjk2ZTJiMzQyOTAxYmQ1MTk3NzFhYjMyZGUzMzBlZDBlMjRjOTBhZA==

