apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatapp.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
      nodePort: {{ .Values.backend.service.nodePort }}
  type: {{ .Values.backend.service.type }}
