apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatapp.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
#     protocol: {{ .Values.frontend.service.protocol | default "TCP" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
  type: {{ .Values.frontend.service.type }}
