apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongo.storage.pvcName }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.storage.size }}
  storageClassName: {{ .Values.mongo.storage.className }}
