apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatapp.fullname" . }}-mongo-service
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
