apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.secret.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.secret.rootUsername | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.secret.rootPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.mongo.secret.jwtSecret | b64enc | quote }}
